Support multiple file upload validation
nestjs/nest pull request #10343
Opened 2022-10-03 14:19 UTC by blangley28

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently file validation via the `ParseFilePipe` only works when validating a single file. When using an array of files it always throws an error.

Issue Number: N/A

## What is the new behavior?

Single file validation continues to work unchanged, but now when uploading multiple files:
1. `fileIsRequired` works 
2. Each file in the array is validated

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2022-10-03 16:45 UTC, Tony133 approved these changes

2022-10-04 06:51 UTC, kamilmysliwiec commented on packages/common/pipes/file/parse-file.pipe.ts
> +    if (isUndefined(value) || (Array.isArray(value) && isEmpty(value))) {
@thiagomini I think you implemented this pipe, is that correct? 🙌 If so, could you verify this PR?

2022-10-04 13:59 UTC, thiagomini requested changes
First, I would like to thank you for your time invested into this bug fix! I left some suggestions to improve the readability of the code, but of utmost importance is the addition of automated tests that cover this feature. Can you create such tests for the correspondent [spec file](https://github.com/nestjs/nest/blob/519ae699b466bf051c0d24c76f39356acacf92b0/packages/common/test/pipes/file/parse-file.pipe.spec.ts)? Thanks!

2022-10-04 13:59 UTC, thiagomini commented on packages/common/pipes/file/parse-file.pipe.ts
> +    if (isUndefined(value) || (Array.isArray(value) && isEmpty(value))) {
This `if` statement started to grow its logic here. Could you wrap this into a private method and give it a meaningful name? something like:

```suggestion
    if (this.thereAreNoFilesIn(value)) {
```

2022-10-04 13:59 UTC, thiagomini commented on packages/common/pipes/file/parse-file.pipe.ts
> +      }
This is a nit as well, but we have an `if` statement nested here along with the `else` condition, increasing a bit of the cognitive complexity here. Would you mind also wrapping this block inside a private method? Something like:

```suggestion
      this.validateFilesFrom(value)
```

and inside this private method, you just paste the same logic.

2022-10-06 20:29 UTC, thiagomini commented
Hey @blangley28 , could you work on the changes I've asked? Thanks!

2022-10-07 19:19 UTC, blangley28 commented
@thiagomini sorry for the delay. Just pushed some updated. I also found that while using `FileFieldInterceptor` the type of `value` is an object. So I added some handling to that here. 
Because both the object and array use the same `Promise.all` snippet I wanted to break that out into a function. There are quite alot of `validate%` methods now... let me know if you have any name suggestions!

2022-10-07 19:25 UTC, Tony133 reviewed
I have reported missing some semicolons in some code statements

2022-10-07 19:25 UTC, Tony133 commented on packages/common/pipes/file/parse-file.pipe.ts
> +    return Promise.all(files.map(f => this.validate(f)))
```suggestion
    return Promise.all(files.map(f => this.validate(f)));
```

2022-10-07 19:25 UTC, Tony133 commented on packages/common/pipes/file/parse-file.pipe.ts
> +    return isUndefined(value) || isEmptyArray || isEmptyObject
```suggestion
    const isEmptyArray = (Array.isArray(value) && isEmpty(value));
    const isEmptyObject = isObject(value) && isEmpty(Object.keys(value));
    return isUndefined(value) || isEmptyArray || isEmptyObject;
```

2022-10-07 19:25 UTC, Tony133 commented on packages/common/pipes/file/parse-file.pipe.ts
> +      await this.validateFiles(files)
```suggestion
      const files = [].concat(...Object.values(value));
      await this.validateFiles(files);
```

2022-10-07 19:25 UTC, Tony133 commented on packages/common/pipes/file/parse-file.pipe.ts
> +      await this.validateFiles(value)
```suggestion
      await this.validateFiles(value);
```

2022-10-07 19:25 UTC, Tony133 commented on packages/common/pipes/file/parse-file.pipe.ts
> +      this.validateAllFrom(value)
```suggestion
      this.validateAllFrom(value);
```

2022-10-10 12:13 UTC, thiagomini commented
> @thiagomini sorry for the delay. Just pushed some updated. I also found that while using `FileFieldInterceptor` the type of `value` is an object. So I added some handling to that here. Because both the object and array use the same `Promise.all` snippet I wanted to break that out into a function. There are quite alot of `validate%` methods now... let me know if you have any name suggestions!

No problem @blangley28! Now you only have to fix the tests and add the new ones.

2022-12-02 23:11 UTC, PhelixTaken commented
Hello,

Is this being continued? I really would like to have this since I need to validate multiple files.
I made my own implementation, but would rather not use that and just use the native stuff.

I hope it gets merged soon!

2022-12-05 12:20 UTC, thiagomini commented
Hey @PhelixTaken. We cannot merge this PR until it has all tests passing. You are welcome to create a branch that resolves this problem as well, I would be happy to review it! I can work on that issue too once I have some time, but I can't promise you a date.

2022-12-07 20:39 UTC, mahkassem commented
Thank you for the great efforts.

I want to add that `thereAreNoFilesIn()` method is not working if the value is array but empty.
this worked for me:
```ts
private thereAreNoFilesIn(value: any): boolean {
    if (Array.isArray(value)) {
        return value.length === 0;
    } else if (isObject(value)) {
        return Object.keys(value).length === 0;
    } else {
        return isEmpty(value);
    }
}
``` 

also `isUndefined()` is deprecated, I have edited this to use `value === undefined`

I would love to help in this PR. just let me know :)

2023-02-01 12:19 UTC, kamilmysliwiec commented
Let's track this here https://github.com/nestjs/nest/pull/10737

2023-02-01 12:19 UTC, closed without merging