feat(websockets): add prefix option for api versioning
nestjs/nest pull request #10597
Opened 2022-11-24 13:31 UTC by notusertelken

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Websocket gateway options has only `path` and no 'prefix'

Issue Number: (https://github.com/nestjs/nest/issues/9376)

## What is the new behavior?
websocket gateway options now has `path` and `prefix` which get joined for the full path. this can be used for api versioning

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2022-11-24 22:53 UTC, Tony133 requested changes

2022-11-24 22:53 UTC, Tony133 commented on packages/websockets/socket-server-provider.ts
> +    console.log(options);
```suggestion
```
The `console.log()` should be removed

2022-11-26 10:29 UTC, Tony133 approved these changes

2023-01-24 01:15 UTC, micalevisk commented on packages/websockets/interfaces/gateway-metadata.interface.ts
> +  prefix?: string;
since we have prefix and versioning for `@Controller()`, I found _"using `prefix` for api version"_ a bit strange

Can't we avoid mention that specific use case? :thinking:

2023-01-24 14:14 UTC, micalevisk commented on packages/websockets/interfaces/gateway-metadata.interface.ts
> +  prefix?: string;
yep

2023-02-06 01:53 UTC, micalevisk commented on packages/websockets/test/utils/socket-gateway.decorator.spec.ts
> +  @WebSocketGateway({ namespace: '/', path: '/path', prefix: '/prefix' })
can we add another test solely to check if the prefix is being added, instead of replacing this one that has no prefix? so we will test both versions

2024-11-20 13:26 UTC, kamilmysliwiec commented
I'm doing some housekeeping and finally got around to this issue (2 years later nice)

WebSocket versioning could be useful if it were integrated with the app.enableVersioning feature, providing HTTP-like versioning support. However, if it's simply a prefix set in the decorator, that can already be achieved through manual path concatenation.

Thanks for your contribution anyway!

2024-11-20 13:26 UTC, closed without merging