feat(microservice): TCP microservice over TLS
nestjs/nest pull request #10628
Opened 2022-12-02 22:18 UTC by nomaxg

Builds off of @Flusinerd's work to add the option to connect to a TCP microservice over TLS.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

Adds the ability to pass through TLS options to both the client and the server by means of an optional `tlsOptions` property. 

- [ ] Bugfix
- [ x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/nestjs/nest/issues/6745

## What is the new behavior?
If `tlsOptions` are specified, a tls server will be instantiated server-side, and a TLSSocket will be used to connect to the server client-side. Under the hood, options are passed down to the Node [tls library](https://nodejs.org/api/tls.html]). 

## Does this PR introduce a breaking change?
- [ ] Yes
- [ x] No

## Other information

2022-12-09 19:51 UTC, Flusinerd commented
I can confirm, that he sample builds for me as well.

![image](https://user-images.githubusercontent.com/22977969/206785393-7c0d6b65-3596-4498-acf7-cfe2bf9f66bc.png)

Still looking into why it failed on ci, but pretty hard to reproduce

2022-12-09 20:22 UTC, Flusinerd requested changes
Seems like you mixed ``ConnectionOptions`` and ``TlsOptions``

2022-12-09 20:22 UTC, Flusinerd commented on packages/microservices/client/client-tcp.ts
> +  public tlsOptions?: ConnectionOptions;
You are using ``ConnectionOptions`` here

2022-12-09 20:22 UTC, Flusinerd commented on packages/microservices/interfaces/microservice-configuration.interface.ts
> +    tlsOptions?: TlsOptions;
And you are using ``TlsOptions`` here

```suggestion
    tlsOptions?: ConnectionOptions;
```

2022-12-09 20:22 UTC, Flusinerd commented on packages/microservices/interfaces/microservice-configuration.interface.ts
> +    tlsOptions?: TlsOptions;
And you are using ``TlsOptions`` here

```suggestion
    tlsOptions?: ConnectionOptions;
```

2022-12-09 20:22 UTC, Flusinerd commented on packages/microservices/interfaces/microservice-configuration.interface.ts
> +    tlsOptions?: TlsOptions;
And you are using ``TlsOptions`` here

```suggestion
    tlsOptions?: ConnectionOptions;
```

2022-12-09 20:22 UTC, Flusinerd commented on packages/microservices/interfaces/microservice-configuration.interface.ts
> +import { TlsOptions } from 'tls';
Update the import
```suggestion
import { ConnectionOptions } from 'tls';
```

2023-01-04 18:47 UTC, nomaxg commented
> Seems like you mixed `ConnectionOptions` and `TlsOptions`

thanks! updated

2023-01-04 19:04 UTC, nomaxg commented
> > Seems like you mixed `ConnectionOptions` and `TlsOptions`
> 
> thanks! updated

Actually I believe that the configuration was correct before - `ClientTCP` should use `ConnectionOptions` in the call to [`tls.connect`](https://microsoft.github.io/PowerBI-JavaScript/modules/_node_modules__types_node_tls_d_._tls_.html#connect)

2023-02-01 12:05 UTC, kamilmysliwiec commented
`samples` workflow is now failing with the following error:

![image](https://user-images.githubusercontent.com/23244943/216037992-ebf98bcf-bcfa-4b7d-a5f4-7abc3402b69e.png)

2023-02-01 12:06 UTC, kamilmysliwiec commented on packages/microservices/client/client-tcp.ts
> +    }
What was the reason for moving this up? We should also add an inline comment on why "connect" is not required for tls

2023-02-23 16:27 UTC, nomaxg commented on packages/microservices/client/client-tcp.ts
> +    }
Moved this back to its original location, added a comment

2023-02-23 16:46 UTC, nomaxg commented
Thanks for the review, @kamilmysliwiec. Fixed the samples failure by using `ConnectionOptions` instead  of `TlsOptions` in `TcpOptions` (@Flusinerd you were correct about this). Added an inline comment explaining why connecting twice isn't necessary for tls sockets.

2023-04-05 08:46 UTC, merged

2023-04-05 08:46 UTC, kamilmysliwiec commented
LGTM

2023-04-05 10:48 UTC, kamilmysliwiec commented
Would you like to create a PR to the docs (with an additional section about this feature) @nomaxg? This could be based off this PR https://github.com/nestjs/docs.nestjs.com/pull/1961