Refactor define type
nestjs/nest pull request #11040
Opened 2023-02-03 20:09 UTC by mohamadrezamomeni

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2023-02-03 21:09 UTC, mohamadrezamomeni commented
define type for file details input in pipes

2023-02-03 22:56 UTC, micalevisk commented
as `FileTypeValidator` is a public API, this PR introduces a breaking change.

2023-02-04 06:34 UTC, mohamadrezamomeni commented
I think it is better to define type for inputs.

2023-02-04 07:49 UTC, mohamadrezamomeni commented
> as `FileTypeValidator` is a public API, this PR introduces breaking changes.

2023-02-04 07:50 UTC, mohamadrezamomeni commented
> as `FileTypeValidator` is a public API, this PR introduces breaking changes.

thank you for comment.

2023-02-04 08:39 UTC, mohamadrezamomeni commented
> as `FileTypeValidator` is a public API, this PR introduces breaking changes.
i want to change any type for file to specific interface. then write unit test based on this interface. is it acceptable?

2023-02-06 08:55 UTC, kamilmysliwiec commented
@thiagomini want to take a look? 👀

2023-02-06 16:34 UTC, micalevisk commented
@mohamadrezamomeni sounds good

2023-02-06 17:00 UTC, thiagomini requested changes
Thank you for your contribution! I think we only need to adjust a few things, tho. Check my suggestions below.

2023-02-06 18:53 UTC, mohamadrezamomeni commented on packages/common/pipes/file/interfaces/file.interface.ts
> +}
thank you for reviewing my code and for giving suggestion. I solve it this issue

2023-02-06 20:07 UTC, mohamadrezamomeni commented
@thiagomini what is your opinion right now ? :)

2023-02-06 21:12 UTC, mohamadrezamomeni commented
> @thiagomini what is your opinion right now ? :)

according to the unit test, I choose TFile extends IFile | {} type for input of isValid method because input of is empty object or object include size or mimetype.

2023-02-07 21:35 UTC, mohamadrezamomeni commented
@kamilmysliwiec I would like to know your opinion:)

2023-02-07 21:56 UTC, mohamadrezamomeni commented
> @thiagomini what is your opinion right now ? :)

2023-02-07 22:08 UTC, thiagomini commented
Hey, man, I'll review this PR again tomorrow. The last two days have been quite busy around here 😅.  Thanks again for the contribution.

2023-02-09 11:10 UTC, thiagomini approved these changes
This LGTM now, but there's only one question left: why did you add the ` || { }` in the generic type?

2023-02-09 12:12 UTC, mohamadrezamomeni commented
> This LGTM now, but there's only one question left: why did you add the ` || { }` in the generic type?

It is issue i put ` || { }` because according to the test input of isValue may be empty object. can you guide me what to do for this problem

2023-02-09 12:22 UTC, thiagomini commented
> > This LGTM now, but there's only one question left: why did you add the ` || { }` in the generic type?
> 
> It is issue i put ` || { }` because according to the test input of isValue may be empty object. can you guide me what to do for this problem? i wanted to use // // @ts-ignore in unit test but i don't know it is good idea or no

I think we don't have to be explicit about that. The `any` case should already cover it.

2023-02-09 12:53 UTC, mohamadrezamomeni commented
> I think we don't have to be explicit about that. The `any` case should already cover it.

do it :)

2023-03-10 13:11 UTC, mohamadrezamomeni commented
@kamilmysliwiec  do you have any opinion right now?

2023-04-05 11:07 UTC, merged