feat(core): add factory-provider circular dependency check
nestjs/nest pull request #11126
Opened 2023-02-16 22:31 UTC by Flusinerd

add check in container.ts to check if a circular dependency is detected between factory providers. add integration test to check for error message with circular dependency Circular dependency between two factory providers

closes #11093

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #11093 

Currently the nest application won't start when there is a circular dependency between factory providers

## What is the new behavior?

A descriptive error will be thrown when a circular dependency is detected.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information
WIP: Unit-Tests.

2023-02-18 11:54 UTC, micalevisk commented on integration/injector/e2e/circular-factory-providers.spec.ts
> +    // Assert that the Error is thrown
```suggestion
```

2023-02-20 07:38 UTC, kamilmysliwiec requested changes

2023-02-20 07:38 UTC, kamilmysliwiec commented on packages/core/injector/container.ts
> +    if (isFactoryProvider(provider)) {
Are we sure that we want to run `detectCircularDependencyBetweenFactoryProviders` for every single factory provider?

AFAIR we should be able to fix this issue by tweaking Injector's implementation. The container class shouldn't be responsible for this

2023-04-05 08:48 UTC, closed without merging

2023-07-03 21:27 UTC, Flusinerd commented
Hi @kamilmysliwiec 
Sorry I did not have much time lately but want to get this solved now.

I did some further research and can think of this solution:

We could make use of the ``InstanceMetadataStore.dependencies`` array to check for circular dependencies inside the injector:

For example, these provider construct:
```ts
export const dynamicProvider1 = {
  provide: 'PROVIDER1',
  useFactory: (provider2: any) => {
    return {
      name: 'provider 1',
    };
  },
  inject: ['PROVIDER2'],
};

export const dynamicProvider2 = {
  provide: 'PROVIDER2',
  useFactory: (provider1: any) => {
    return {
      name: 'provider 2',
    };
  },
  inject: ['PROVIDER1'],
};
```
would result in this while resolving ``PROVIDER1`` for ``PROVIDER2``

``InstanceWrapper(PROVIDER1).instance_metadata``:
```
dependencies: [{
  name: 'PROVIDER2' // Everything is fine here
  instance_metadata: {
    dependencies: [{
      name: 'PROVIDER1'// HERE the circular dependencie occurs, because we encounter PROVIDER1 while resolving PROVIDER1
    }]
}];
```

Would this be a suitable solution?

This check could for example occur here:
https://github.com/nestjs/nest/blob/883d0fb8a874b359c54dd541cde206c9c23d790e/packages/core/injector/injector.ts#L514

2023-07-04 21:24 UTC, Flusinerd commented
This would be my proposed solution:
```ts
public async resolveComponentInstance<T>(
    moduleRef: Module,
    token: InjectionToken,
    dependencyContext: InjectorDependencyContext,
    wrapper: InstanceWrapper<T>,
    contextId = STATIC_CONTEXT,
    inquirer?: InstanceWrapper,
    keyOrIndex?: symbol | string | number,
  ): Promise<InstanceWrapper> {
    this.printResolvingDependenciesLog(token, inquirer);
    this.printLookingForProviderLog(token, moduleRef);
    const providers = moduleRef.providers;
    const instanceWrapper = await this.lookupComponent(
      providers,
      moduleRef,
      { ...dependencyContext, name: token },
      wrapper,
      contextId,
      inquirer,
      keyOrIndex,
    );
   
    // Start of changes
    if (!isNil(instanceWrapper.inject)) {
      const encounteredDependencies = new Set<InjectionToken>();
      const checkForCircularDependency = (instance: InstanceWrapper) => {
        const dependencies = instance[INSTANCE_METADATA_SYMBOL].dependencies;
        dependencies.forEach(dep => {
          if (encounteredDependencies.has(dep.token)) {
            const injectionPath = [...encounteredDependencies, dep.token].map(
              token => token.toString(),
            );
            throw new CircularDependencyFactoryProviderException(injectionPath);
          }

          if (!isNil(dep.inject)) {
            encounteredDependencies.add(dep.token);
            checkForCircularDependency(dep);
          }
        });
      };

      checkForCircularDependency(instanceWrapper);
    }
    // End of changes

    return this.resolveComponentHost(
      moduleRef,
      instanceWrapper,
      contextId,
      inquirer,
    );
  }
```

This is basically using the Instancewrapper metadata as a dependency tree and a depth first search to detect the circular dependency utilizing the injection token. So this also works for: ``PROVIDER1 -> PROVIDER2 -> PROVIDER3 -> PROVIDER1``