fix(core): fix flaky durable providers
nestjs/nest pull request #11666
Opened 2023-05-25 15:00 UTC by KamalAman

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #11664

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2023-05-25 15:04 UTC, micalevisk commented on integration/scopes/e2e/durable-providers.spec.ts
> +      // const constructorStub = sinon.stub(DurableService, 'constructor').throws(new Error('test error'));
I don't know neither :/ I will try to find something later

2023-05-25 15:05 UTC, micalevisk requested changes
can you please remove the `yarn.lock`

2023-05-30 17:28 UTC, KamalAman commented
i'll try to get back to this over the weekend and close it off

2024-10-23 06:20 UTC, dberardo-com commented
@KamalAman @kamilmysliwiec  what was the reason why this PR was never accepted ? i reopened an issue on the matter: https://github.com/nestjs/nest/issues/13953

2024-10-23 12:25 UTC, KamalAman commented
@dberardo-com yeah this is an annoying bug. I never figured out how to test it. Anyone who wants to pick it up, please feel free to take this over.

2024-11-12 12:26 UTC, closed without merging