feat(core): check providers and controllers
nestjs/nest pull request #11893
Opened 2023-06-24 21:00 UTC by odoldotol

check if providers are Injectable or customProvider and if controllers are controller.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #11890

check if providers are Injectable or customProvider.
check if controllers are controller.

It is not allowed unreasonable things, such as using controller as provider or provider as controllers.

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2023-06-24 22:29 UTC, odoldotol commented
It is suspected that the issue may be caused by the dummy Provider used in various tests.

Allowing Providers other than Controllers would be acceptable as a modification, but it does not meet the level of control I desire.

Nevertheless, I wil attempt to modify the code using this approach.

2023-06-24 23:09 UTC, micalevisk requested changes
instead of raising an exception we must just log out an warning message like I did here: https://github.com/nestjs/nest/commit/b995c22528098c57df4a2a0e79e814dc380ed98c#diff-aa35faacdaa9a8edcbeafc195044ee0e8166425c338488d89dc465d0947d88ffR157 otherwise we're introducing a breaking change.

Also please add a `// TODO(v11)` to remind ourselfs on transforming the warning into a `throw` later in nestjs v11

2023-06-25 02:29 UTC, odoldotol commented
@micalevisk Thx :)

2023-06-25 02:33 UTC, micalevisk reviewed
Looks good so far

But I believe that the new code doesn't follows the formatting rules. Can you run `npm run format` (and commit only the files you've changed)

2023-06-25 02:48 UTC, odoldotol commented
@micalevisk 
run it, but nothing changed.

2023-06-25 02:53 UTC, micalevisk approved these changes

2023-06-25 03:02 UTC, jmcdo29 commented on packages/core/errors/messages.ts
> +  return `Classes not annotated with @Injectable() decorator or Objects that are not 'Custom Provider' cannot be registered as providers.
This isn't entirely true, as `@Resolver()` and `@WebSocketGateway(0` are registered via `providers`, plus, this would break `nest-commander`, `ogma`, and `necord`, which all have custom decorators to trigger the metadata to be emitted via `tsc` (or similar), but don't need `@Injectable()` to be valid providers

2023-06-25 03:08 UTC, odoldotol commented on packages/core/errors/messages.ts
> +  return `Classes not annotated with @Injectable() decorator or Objects that are not 'Custom Provider' cannot be registered as providers.
@jmcdo29
it seems I overlooked something.
So, should we just block the controllers or are there any other aspects to consider?
I'm curious to know your opinion.

2023-06-25 03:29 UTC, jmcdo29 commented on packages/core/errors/messages.ts
> +  return `Classes not annotated with @Injectable() decorator or Objects that are not 'Custom Provider' cannot be registered as providers.
I think restricting just the controllers, similar to how we did for `imports` and ensuring providers weren't added there, will be enough. 

In the end, providers are the most general concept, and technically even exception filters (`@Catch()`) can be added to the array for a valid use case (`useExisting`), so keeping that array as open as possible would be better than restricting it.

2023-06-25 03:45 UTC, odoldotol commented on packages/core/errors/messages.ts
> +  return `Classes not annotated with @Injectable() decorator or Objects that are not 'Custom Provider' cannot be registered as providers.
Yes, that’s right.
It is appropriate to restrict providers only to prevent minimal misuse while leaving the rest open.
Thank you.

2023-06-26 09:03 UTC, kamilmysliwiec commented on packages/core/errors/messages.ts
> +  return `Classes not annotated with @Injectable() decorator or Objects that are not 'Custom Provider' cannot be registered as providers.
I don't think we should restrict controllers from being registered as providers, too. This may sometimes make sense, for example in tests (when you want a class to be instantiated by the Nest container but at the same time, you don't routes to be exposed/introspected by other libs, be it `@nestjs/swagger` for instance).

2023-06-27 01:16 UTC, micalevisk approved these changes

2023-07-05 12:47 UTC, InyerM10 approved these changes

2023-07-12 15:54 UTC, rubiin approved these changes

2023-07-14 01:25 UTC, micalevisk commented on packages/core/errors/messages.ts
> +  return `Classes not annotated with @Injectable() decorator or Objects that are not 'Custom Provider' cannot be registered as providers.
I just notice that we already has such checking for anything that doesn't have the `@Controller()` decorator but was added to the `controllers` arrays. See:

https://github.com/nestjs/nest/blob/e36f04c51eb5c2a9ebc64b4314e7b238b14448e9/packages/core/test/router/router-explorer.spec.ts#L156-L163
![image](https://github.com/nestjs/nest/assets/13461315/7721d144-f7aa-4ae5-9536-a5e5df7adf5d)


So we can close this PR, IMO.

2023-07-14 02:58 UTC, odoldotol commented on packages/core/errors/messages.ts
> +  return `Classes not annotated with @Injectable() decorator or Objects that are not 'Custom Provider' cannot be registered as providers.
Oh, I checked it.
Yes, you can.
thank you.

2023-07-14 06:33 UTC, closed without merging