feat(common): adding the fieldname to validation errors
nestjs/nest pull request #12403
Opened 2023-09-18 07:51 UTC by sezanzeb

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #12357

It's impossible to know based on the BadRequest response payload which field is causing problems

## What is the new behavior?

The error message contains the field name

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2023-09-18 07:51 UTC, sezanzeb commented
test missing

2023-09-19 18:32 UTC, rubiin approved these changes

2023-09-25 09:22 UTC, quangtran88 approved these changes

2023-09-29 01:35 UTC, benjGam approved these changes
Thanks mate for this update, it will be usefull to do not do it manually for each new project.

2023-09-29 21:09 UTC, jmcdo29 commented
Should we also add the `metadata.type` so if there are multiple `foo` fields the user knows which one specifically caused the error (body, query, param, custom)?

2023-10-04 07:45 UTC, sezanzeb commented
I'm using those pipes together with a custom pipes to extract values from a nested payload.

If my body is like

```json
{
  "foo": {
    "bar": "qux"
  }
}
```

I'll have to use something like `@Body('foo', GetBar, ParseIntPipe)`

This would cause the error message to be `Validation failed (numeric string is expected in "foo")`.

I would much rather like this to be something like `Validation failed (numeric string is expected in "foo.bar")`

One solution I can think of, which would work for my use-case, is to create a custom decorator, like `@BodyFoo('bar')`, and to add a new optional field to metadata called `name`. My custom decorator could then overwrite `metadata.name` with `"foo.bar"`.

2023-10-04 07:48 UTC, sezanzeb commented
Another one might be to support using an array instead of a string: `@Body(['foo', 'bar'], ParseIntPipe)` for nested attributes.

2023-12-31 10:37 UTC, benjGam requested changes
Hey, i looked to your code, and i enjoy the changes, but is it possible to add an way to turn off/on this ? Like do not force anybody to include field name in message, but instead add a (decorator ?) to apply or not this behavior ?

2024-11-18 12:33 UTC, kamilmysliwiec commented
I agree that we should enable this behind a flag (so everyone can turn it on/off depending on what they want)

2024-11-18 17:21 UTC, sezanzeb commented
> Hey, i looked to your code, and i enjoy the changes, but is it possible to add an way to turn off/on this ? Like do not force anybody to include field name in message, but instead add a (decorator ?) to apply or not this behavior ?

Oh, sorry, I somehow totally missed your comment. I haven't used NestJs in a while, and it would take some time to really get into the details of this PR and nestjs decorators again. Therefore I unfortunately can't tell if this could be switched on or off somehow.

If anyone is interested in continuing work on this, feel free to fork my branch and create a new PR, I guess.

2024-11-20 09:30 UTC, closed without merging