feat: emit batch
nestjs/nest pull request #12954
Opened 2023-12-20 08:03 UTC by gunb0s

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #12748

## What is the new behavior?

enable kafka producer to emit batch

## Does this PR introduce a breaking change?
- [v] Yes
- [ ] No

## Other information

2023-12-20 23:05 UTC, Tony133 requested changes
For the rest it seems ok 👍

2023-12-20 23:05 UTC, Tony133 commented on packages/microservices/client/client-kafka.ts
> +    if (packets.data.messages.length === 0) return;
```suggestion
    if (packets.data.messages.length === 0) {
       return;
    }
```

2023-12-21 01:27 UTC, gunb0s commented on packages/microservices/client/client-kafka.ts
> +    if (packets.data.messages.length === 0) return;
[feat: add block wrapping return](https://github.com/nestjs/nest/pull/12954/commits/cb8e04dd62d85f37b61936f53a50f1bb8169e52c)

2023-12-21 07:19 UTC, Tony133 approved these changes

2024-01-23 20:11 UTC, apparelmagic-heath commented
Would love to see this feature merged. Very handy for our use-case.

2024-03-11 14:13 UTC, bozorgmehr96 commented
Is this going to be merged, and if so, do you have any estimates for when?

And another thing, are you open to batching now? You said no here, #9455
Since you green-lighted batch producing, I need batch consuming and want to know if I should also have hope for it. I might start a PR for it if I find some free time.

2024-04-14 07:12 UTC, binh-truong-tpv-mti commented
hi all, pls consider this PR

2024-11-13 05:36 UTC, posquit0 commented
@Tony133 @kamilmysliwiec I need this feature, too! Could you consider to merge this PR?

2024-11-13 07:52 UTC, Tony133 commented
> @Tony133 @kamilmysliwiec I need this feature, too! Could you consider to merge this PR?

It need to be seen whether it can be merged into version 10.x of NestJS or put into the future version 11.

2024-11-20 10:11 UTC, merged