fix: type narrowing ctx
nestjs/nest pull request #14126
Opened 2024-11-10 07:36 UTC by EeeasyCode

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #14093 

The context parameter in createParamDecorator callback currently has an any type, which reduces type safety. Developers are unable to leverage the type-checking benefits of TypeScript when working with this parameter.

## What is the new behavior?

The context parameter in the createParamDecorator callback now has a narrower type of ExecutionContext. This allows developers to benefit from TypeScript’s type-checking capabilities, improving code quality and reducing potential errors when using this parameter in decorators.

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

This change improves type safety and aligns with TypeScript best practices by eliminating unnecessary any types. Tests have been added to validate that the context parameter is indeed typed as ExecutionContext. Additional documentation has been updated to reflect this enhancement.

2024-11-10 13:58 UTC, micalevisk requested changes

2024-11-10 13:58 UTC, micalevisk commented on packages/common/interfaces/features/custom-route-param-factory.interface.ts
> +import { ExecutionContext } from '..';
Can you please import this from the file instead of from the barrel file

2024-11-10 15:07 UTC, EeeasyCode commented on packages/common/interfaces/features/custom-route-param-factory.interface.ts
> +import { ExecutionContext } from '..';
@micalevisk 
Sure, I have just [updated the code](https://github.com/nestjs/nest/pull/14126/commits/2874478b958e5f4c4ab57acf8694c26abdf6227a) with the mentioned changes. Please check!

Thank you for the feedback.

2024-11-12 08:36 UTC, kamilmysliwiec commented
LGTM

2024-11-12 08:36 UTC, merged