feat(sse): Implement Server-Sent Events
nestjs/nest pull request #4842
Opened 2020-05-25 10:40 UTC by soyuka

## PR Checklist

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

```
[x] Feature see #4826
```

See discussion in #4826. This is a work in progress I need to validate the implementation before handling unit tests. You can test this using the new sample 28.

Usage:

```
@Controller()
export class AppController {
  @Get()
  getHello(): string {
    return `
    <script type="text/javascript">
      const ee = new EventSource('/sse')
      ee.onmessage = ({data}) => {
        console.log('New message', JSON.parse(data))
      }
    </script>
    `;
  }

  @Sse('/sse')
  sse(): Observable<MessageEvent> {
    return interval(1000).pipe(map((_) => ({ data: { hello: 'world' } })));
  }
}
```

2020-05-25 10:41 UTC, soyuka commented on packages/core/helpers/handler-metadata-storage.ts
>    ) => any;
not a fan of this change @kamilmysliwiec do you have a suggestion to maybe handle the sseStream elsewhere?

2020-05-25 10:42 UTC, soyuka commented on packages/core/router/router-response-controller.ts
> +    }
I don't see much interest in not using Observables for this task, would you suggest another way of handling typing/errors?

2020-05-25 10:43 UTC, soyuka commented on packages/core/router/router-response-controller.ts
> +    request: any,
Don't know yet how to handle these, but let's clear this after validating the implementation according to the router context execution.

2020-05-25 10:52 UTC, tonivj5 commented on packages/common/decorators/http/sse.decorator.ts
> +export function Sse(path?: string): MethodDecorator {
WDYT about `SSE` instead of `Sse`?

2020-05-25 12:25 UTC, soyuka commented on packages/common/decorators/http/sse.decorator.ts
> +export function Sse(path?: string): MethodDecorator {
We're naming `Http` not `HTTP` in class names and `Get` not `GET` for decorators.

2020-05-29 07:33 UTC, kamilmysliwiec commented on sample/28-sse/README.md
> +<p align="center">
Can we remove the `28-sse`? I don't think it makes sense to create a separate sample for this (likewise, we don't have dedicated samples for `@Redirect()` or any similar decorators)

2020-05-29 07:33 UTC, kamilmysliwiec commented on packages/common/http/index.ts
> +export { SseStream } from './sse-stream.service';
The `http` directory is exclusively created for the `HttpModule`.  Can we move this file elsewhere? (+ my recommendation would be `core` package instead)

2020-05-29 07:35 UTC, kamilmysliwiec commented on packages/core/helpers/handler-metadata-storage.ts
>    ) => any;
not a fan of this change either, but `fnHandleResponse` seems to be the only way :( Ill think about what we can do

2020-05-29 07:36 UTC, kamilmysliwiec commented on packages/core/router/router-response-controller.ts
> +    }
> I don't see much interest in not using Observables for this task

Fully agree.

> would you suggest another way of handling typing/errors

I think your approach is fine.

2020-05-29 10:25 UTC, soyuka commented on packages/common/http/index.ts
> +export { SseStream } from './sse-stream.service';
:+1: will move this to `core`

2020-05-29 10:27 UTC, soyuka commented on sample/28-sse/README.md
> +<p align="center">
I see this @Sse directive as we could see the Websocket one. I think that this may serve as a functional test or a test application to understand how it works and to understand that it can be used for real-time updates.

2020-05-29 10:43 UTC, tonivj5 commented on packages/common/decorators/http/sse.decorator.ts
> +export function Sse(path?: string): MethodDecorator {
Yeah, you're right :+1:

2020-07-29 11:16 UTC, kamilmysliwiec commented
The overall API looks good! Would you like to create a PR to the docs? We can add it under the "Techniques" category (as a new, dedicated page) or just add a new section in the "Controllers" chapter

2020-07-29 12:29 UTC, soyuka commented
see https://github.com/nestjs/docs.nestjs.com/pull/1387 lmk if I should rebase

2020-07-30 07:30 UTC, soyuka commented
rebased and added docs

2020-08-15 11:52 UTC, jdgriffith commented
Any chance this will land soon? Our team could use this feature :)

2020-08-18 15:05 UTC, soyuka commented
> Any chance this will land soon? Our team could use this feature :)

Would you be able to test my branch and make some feedbacks?

2020-08-19 09:51 UTC, dunglas requested changes

2020-08-19 09:51 UTC, dunglas commented on packages/core/services/sse-stream.service.ts
> +        'Content-Type': 'text/event-stream; charset=utf-8',
`charset=utf-8` is optional (and useless here).

2020-08-19 09:51 UTC, dunglas commented on packages/core/services/sse-stream.service.ts
> +        'Cache-Control': 'no-cache',
To ensure compatibility with a wide range of proxies (including Fastly and Nginx), you should copy all these headers: https://github.com/dunglas/mercure/blob/master/hub/subscribe.go#L124-L130

2020-08-19 09:51 UTC, dunglas commented on packages/core/services/sse-stream.service.ts
> +      this.lastEventId = this.lastEventId === null ? 0 : this.lastEventId + 1;
nitpicking: `this.lastEventId++` does the trick (`var foo = null; foo++; // foo = 0`)

2020-08-19 09:51 UTC, dunglas commented on packages/core/services/sse-stream.service.ts
> +      message.id = '' + this.lastEventId;
`this.lastEventId.toString()` ?

2020-08-19 09:51 UTC, dunglas commented on packages/core/services/sse-stream.service.ts
> +      message.type = 'message';
This field can be omitted if its value is "message" to save a few bytes on the wire.

2020-08-19 09:51 UTC, dunglas commented on packages/core/services/sse-stream.service.ts
> +    destination.write(':ok\n');
Why not just `:`?

2020-08-19 10:01 UTC, dunglas commented on packages/core/services/sse-stream.service.ts
> +      this.lastEventId = this.lastEventId === null ? 0 : this.lastEventId + 1;
Or you can just initialize the field to -1 if TypeScript raises an issue.

2020-09-03 03:55 UTC, mfcodeworks commented
Any chance for this being merged soon? Would love to provide SSE updates to clients

2020-09-03 18:38 UTC, lukeheath commented
Same here! This will be a great feature add for the framework.

2020-09-04 09:50 UTC, soyuka commented
> Any chance for this being merged soon? Would love to provide SSE updates to clients
> Same here! This will be a great feature add for the framework.

Same comment as above: Would you be able to test my branch and make some feedbacks?

2020-09-11 17:06 UTC, jmcdo29 commented on packages/core/services/sse-stream.service.ts
> +    if (message.data) data += toDataString(message.data);
If these are going to be single line ifs, would a ternary make more sense?
```
data += message.type ? `event: ${message.type}\n` : ''
```

2020-09-11 17:29 UTC, soyuka commented on packages/core/services/sse-stream.service.ts
> +    if (message.data) data += toDataString(message.data);
But then you have a useless else part, I'm find with both implementations though.

2020-09-11 17:39 UTC, jmcdo29 commented on packages/core/services/sse-stream.service.ts
> +    if (message.data) data += toDataString(message.data);
Personally, I'm not a fan of inline ifs, so if we stay with using `if` statements it should be changed to
```ts
if (message.type) {
  data += `event: ${message.type}\n`;
}
```
And this is what most of Nest's codebase does already even for single line. So ternary, or using braces as necessary should be fine. Just to stay consistent with the rest of the codebase

2020-09-12 10:36 UTC, soyuka commented on packages/core/services/sse-stream.service.ts
> +    if (message.data) data += toDataString(message.data);
fixed

2020-09-25 07:30 UTC, soyuka commented
I have benchmarks where this hits 80k req/s pushed on a single node. I'd love to know what maintainers think of this work!

2020-10-30 13:57 UTC, kamilmysliwiec commented
Thank you for this amazing contribution! This feature will be available in 7.5.0

2020-10-30 13:57 UTC, merged

2020-11-06 23:54 UTC, ruslanguns commented
Nice feature! Thank you !

2020-11-29 16:06 UTC, ningacoding commented
Hello, how do you send data from a service? to an already subscribed client.

 i tried but observables only works in the method scope and when trying to emit data from another endpoint (for example, when another user/client is updating data) the observable just do not emit to the other client to receive the update.

2020-11-30 07:47 UTC, kamilmysliwiec commented
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.