fix(core): patch CVE-2020-15168
nestjs/nest pull request #5666
Opened 2020-11-04 18:02 UTC by mikicho

https://nvd.nist.gov/vuln/detail/CVE-2020-15168

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
patch [CVE-2020-15168](https://nvd.nist.gov/vuln/detail/CVE-2020-15168)

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2020-11-04 18:05 UTC, jmcdo29 requested changes

2020-11-04 18:05 UTC, jmcdo29 commented on packages/core/package.json
>      "@nuxtjs/opencollective": "0.2.2",
Should this be removed like it was in the root `package.json`?

2020-11-04 18:08 UTC, jmcdo29 approved these changes
LGTM

2020-11-04 18:08 UTC, mikicho commented on packages/core/package.json
>      "@nuxtjs/opencollective": "0.2.2",
Yeah, I removed it, I forgot to remove the old package from all the npm stuff :D

2020-11-04 18:09 UTC, jmcdo29 commented
I'll check what the failure is on circleCI, but otherwise the change looks fine

2020-11-04 18:10 UTC, mikicho commented
@jmcdo29 
No need to update the package-lock in the root folder?

2020-11-04 18:14 UTC, jmcdo29 commented
> @jmcdo29
> No need to update the package-lock in the root folder?

Yes, you need to update it. `npm i` should fix that. Tha will also fix the CircleCI failure

2020-11-04 18:18 UTC, mikicho commented
@jmcdo29 I pushed the package-lock after `npm i`. but look on the change look too many changes, also the `lockfileVersion` file changed from 2 to 1.

2020-11-04 18:20 UTC, jmcdo29 commented
Interesting. May need @kamilmysliwiec's opinion on this. Looks like it did fix the build step though

2020-11-05 07:43 UTC, kamilmysliwiec commented
Is there any difference between `@nuxtjs/opencollective` and `@nuxt/opencollective`?

2020-11-05 10:40 UTC, mikicho commented
@kamilmysliwiec this is the same package:
https://github.com/nuxt-contrib/opencollective/issues/62

2020-11-05 10:50 UTC, kamilmysliwiec commented
So is there any reason to switch from `@nuxtjs` to `@nuxt` as part of this PR?

2020-11-05 10:53 UTC, mikicho commented
@kamilmysliwiec `@nuxtjs` is deprecated. they didn't even publish the patch to `@nuxtjs` until I opened that issue.

2020-11-10 09:29 UTC, mikicho commented
@kamilmysliwiec `npm i` sohuld just work? what npm version do we use?

2020-12-08 09:00 UTC, kamilmysliwiec commented
This issue was already addressed by Dependabot https://github.com/nestjs/nest/pull/5746 Anyway, thanks for your contribution!

2020-12-08 09:00 UTC, closed without merging

2020-12-08 12:39 UTC, mikicho commented
@kamilmysliwiec great!

Just, FYI they renamed the package's name. so we may not get future updates