Fix to RMQ socketoptions being incorrectly passed to ampq-connection-manager
nestjs/nest pull request #5790
Opened 2020-11-25 20:01 UTC by christianallred

## PR Type

```
[ x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

RMQ microservices were not properly passing over the the `heartbeatIntervalInSeconds` to the amqp-connection-manager and the only way to get it work as expected was to pass in a url object with the heartbeat value in the object. 

Issue Number: 5788

## What is the new behavior?

I have updated the object being passed to amqp-connection-manager to match the footprint they expect so that socket options are properly accepted. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[ x] No
```

## Other information

2020-11-25 20:34 UTC, jmcdo29 requested changes
Can you add a regression test to ensure this is doing what is expected, and to help it from failing in the future?

2020-11-25 20:34 UTC, jmcdo29 commented on packages/microservices/server/server-rmq.ts
> +     */
While the comment is nice, it should be in the pull request or the commit message so that it's referencable without being in the code.

2020-11-25 20:45 UTC, christianallred commented on packages/microservices/server/server-rmq.ts
> +     */
Updated PR to contain this. removed comment from code. I'll work on a regression test later tonight

2020-11-25 21:52 UTC, christianallred commented
I've added the typings for this as well to help with programming a bit more. if i have time later this week i will add the typings for queueOptions as well. shouldn't be too bad.

2020-11-26 18:19 UTC, christianallred commented
I added the rest of the typings and it caused Integration tests to fail so must be another bug somewhere :) I'll be trying to get tests to run locally tonight or tomorrow i was having trouble getting them running yesterday

2020-12-08 10:37 UTC, kamilmysliwiec commented
Can you please rebase your PR (or cherry-pick your changes)? This PR contains a few unnecessary commits (and changes) unrelated to the actual fix

2020-12-08 20:51 UTC, christianallred commented
> Can you please rebase your PR (or cherry-pick your changes)? This PR contains a few unnecessary commits (and changes) unrelated to the actual fix

Done. Sorry i haven't had time to add the tests. been SUPER busy lately with some real life stuffs.

2020-12-09 12:59 UTC, kamilmysliwiec commented
Thanks!

2020-12-09 12:59 UTC, merged