feat(microservices): log event name w/o handler
nestjs/nest pull request #5813
Opened 2020-11-28 00:58 UTC by poulad

A descriptive error message tells user exactly what event pattern is missing a handler.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: Fixes #5812

## What is the new behavior?
A more descriptive error message. See the discussion on issue.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2020-11-28 04:27 UTC, jmcdo29 requested changes

2020-11-28 04:27 UTC, jmcdo29 commented on packages/microservices/server/server.ts
> +        `${NO_EVENT_HANDLER} Event pattern is ${JSON.stringify(pattern)}.`,
```suggestion
        `${NO_EVENT_HANDLER} Event pattern: ${JSON.stringify(pattern)}.`,
```

2020-11-28 04:27 UTC, jmcdo29 commented on packages/microservices/server/server.ts
> +        `${NO_EVENT_HANDLER} Event pattern is ${JSON.stringify(pattern)}.`,
Either this or `Event pattern requested: ...`

2020-11-28 17:14 UTC, jmcdo29 approved these changes

2020-12-06 14:46 UTC, poulad commented
hey @kamilmysliwiec 
Let me know if any concerns with this PR.

2020-12-08 09:02 UTC, merged

2020-12-08 09:02 UTC, kamilmysliwiec commented
LGTM