fix(common): ParseUUIDPipe - throw exceptions with exceptionFactory only
nestjs/nest pull request #8459
Opened 2021-10-27 23:28 UTC by titivuk

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

`ParseUUIDPipe` supports `exceptionFactory` option. But when it validates not a string, `exceptionFactory` is ignored and `BadRequestException` is thrown from `isUUID` util

## What is the new behavior?
`isUUID` util does not throw an Exception and delegates the decision to `ParseUUIDPipe`

## Does this PR introduce a breaking change?
- [x] Yes
- [ ] No

## Other information

2021-11-01 16:13 UTC, titivuk commented
> We can keep original message and use exceptionFactory to throw correct exception when str is not string (not sure if it's needed). To do so we can remove the util (it's used only in the pipe) and move its code to the pipe file. And, finally, we can add more `ParseUUIDPipe` tests to cover cases related to `exceptionFactory` usage to make sure correct exception is thrown

Done

2021-11-01 16:17 UTC, jmcdo29 commented on packages/common/pipes/parse-uuid.pipe.ts
> +};
Any chance we can make this a `protected` member of the `ParseUUDPipe`, so that if, for whatever reason, someone wanted to they could override/add values to the map?

2021-11-01 17:28 UTC, titivuk commented on packages/common/pipes/parse-uuid.pipe.ts
> +};
Done, uuid reg exp map is protected static property now

2021-11-01 17:29 UTC, jmcdo29 commented on packages/common/pipes/parse-uuid.pipe.ts
> +};
Awesome! Any reason it's static?

2021-11-01 17:41 UTC, titivuk commented on packages/common/pipes/parse-uuid.pipe.ts
> +};
From my point of view it has to be static since the value stays the same for every instance. Moreover, non-static property will be created everytime we use `new ParseUUIDPipe()` which leads to creating the same object over and over again.
Probably it's not a big deal, but as I said static fits better in my opinion

2021-11-01 17:43 UTC, jmcdo29 commented on packages/common/pipes/parse-uuid.pipe.ts
> +};
Good point. Works for me.

2021-11-01 17:43 UTC, jmcdo29 approved these changes
LGTM

2021-12-26 21:04 UTC, micalevisk requested changes

2021-12-26 21:04 UTC, micalevisk commented on packages/common/pipes/parse-uuid.pipe.ts
> +    if (typeof str !== 'string') {
let's DRY this

```suggestion
    if (!isString(str)) {
```

`isString` is imported from `../utils/shared.utils`

2021-12-29 16:39 UTC, titivuk commented on packages/common/pipes/parse-uuid.pipe.ts
> +    if (typeof str !== 'string') {
Fixed, thanks

2021-12-29 16:44 UTC, micalevisk approved these changes

2021-12-29 17:09 UTC, jmcdo29 approved these changes

2022-01-11 15:09 UTC, cikay commented on packages/common/pipes/parse-uuid.pipe.ts
> +    return pattern && pattern.test(str);
Use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

2022-03-05 21:35 UTC, micalevisk commented on packages/common/pipes/parse-uuid.pipe.ts
> +    return pattern && pattern.test(str);
```suggestion
    return pattern?.test(str);
```

2022-03-07 06:32 UTC, bassochette approved these changes

2022-03-07 17:05 UTC, titivuk commented on packages/common/pipes/parse-uuid.pipe.ts
> +    return pattern && pattern.test(str);
Nice catch, didn't notice during refactoring

2022-03-07 17:06 UTC, titivuk commented on packages/common/pipes/parse-uuid.pipe.ts
> +    return pattern && pattern.test(str);
Nice catch

2022-03-07 17:40 UTC, jmcdo29 approved these changes

2022-03-07 18:46 UTC, micalevisk approved these changes

2022-05-17 11:09 UTC, merged