fix(common,core): auto flush logs after `useLogger` call
nestjs/nest pull request #8738
Opened 2021-12-04 04:41 UTC by micalevisk

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #8733

I tested it locally with the following usages:

```js
NestFactory.createApplicationContext(AppModule)
```
flushes.

```js
NestFactory.createApplicationContext(AppModule, { bufferLogs: true })
```
flushes.

```js
NestFactory.createApplicationContext(AppModule, { bufferLogs: true, autoFlushLogs: true })
```
flushes.

```js
NestFactory.createApplicationContext(AppModule, { bufferLogs: true, autoFlushLogs: false })
```
do not flushes.

## What is the new behavior?

When using `NestApplicationContext` app and `autoFlushLogs` is on, invoking `useLogger` method on it will flushes its logs.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

A naive attempt to address that issue without much effort. I have few concerns regarding my solution but I didn't come with anything better (nor easy to follow). Feel free to rejected it then :p

2021-12-04 16:31 UTC, jmcdo29 requested changes
Happy to see this added in. Left a minor comment, but the functionality itself looks fine to me

2021-12-04 16:31 UTC, jmcdo29 commented on packages/core/nest-application-context.ts
> +    if (this.flushLogsOnOverride) this.flushLogs();
Would you mind updating the code to wrap the internals of the if in curly braces? It leads the code to be easier to follow and modify if we need to

```suggestion
    if (this.flushLogsOnOverride) {
      this.flushLogs();
    }
```

2021-12-04 16:31 UTC, jmcdo29 commented on packages/core/nest-factory.ts
> +    if (this.autoFlushLogs) context.shouldFlushLogsOnOverride();
Same as above

2021-12-04 19:14 UTC, micalevisk commented on packages/core/nest-application-context.ts
> +    if (this.flushLogsOnOverride) this.flushLogs();
I prefer your way tbh. I thought `npm run lint:fix` would fix that :p

2021-12-06 11:11 UTC, kamilmysliwiec commented on packages/core/nest-application-context.ts
> +
We can remove the blank line here

2021-12-06 11:12 UTC, kamilmysliwiec commented on packages/core/nest-application-context.ts
> +  public shouldFlushLogsOnOverride() {
`should` word indicates here that this method should return a boolean (and shouldn't update anything itself) - it's a common convention (is/has/should)

2021-12-06 13:48 UTC, micalevisk commented on packages/core/nest-application-context.ts
> +  public shouldFlushLogsOnOverride() {
oh right.

Can we have `shouldFlushLogsOnOverride: boolean`, and `flushLogsOnOverride(): void` method instead? Otherwise I'll add `setFlushLogsOnOverride(value: boolean)`

2021-12-07 08:50 UTC, kamilmysliwiec commented on packages/core/nest-application-context.ts
> +  public shouldFlushLogsOnOverride() {
> Can we have shouldFlushLogsOnOverride: boolean, and flushLogsOnOverride(): void method instead?

Sounds great @micalevisk!

2021-12-16 13:10 UTC, kamilmysliwiec commented on packages/core/nest-application-context.ts
> +  private shouldFlushLogsOnOverride = false;
```suggestion

  private shouldFlushLogsOnOverride = false;
```

2021-12-16 13:11 UTC, merged

2021-12-16 13:11 UTC, kamilmysliwiec commented
LGTM