Add new Feature for Crud Application in Mongoose
nestjs/nest pull request #8992
Opened 2022-01-21 13:29 UTC by asyncfinkd

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
I was looking at your examples and in the Mongoose category you had no choice but to add and get the information in the database. That's why I added get detailed information with _id and delete it at the same time. This I think is better to make users better aware of the work of Nest + Mongoose

## Does this PR introduce a breaking change?
- [x] Yes
- [ ] No

## Other information

2022-01-21 15:28 UTC, jmcdo29 requested changes

2022-01-21 15:28 UTC, jmcdo29 commented on sample/06-mongoose/src/cats/cats.controller.ts
> +  }
These `@Param()`s won't work. `_id` will not match anything in `req.params` so you'll end up with `undefined`. You'd need `@Param('id')` instead, because that's what  you specify it to be in the `@Get()` and `@Delete()`

2022-01-21 18:15 UTC, asyncfinkd reviewed
Fixed

2022-01-24 04:22 UTC, GalloaFranco commented
Hello Nika!, I have a doubt about the use of underscore in the params of `cats.service.ts` and `cats.controller.ts` methods. 
If we stick to the existing Nest documentation, we find that no special naming is used for the token parameter, in fact, the name "id" is kept both in the token param and in the variable to which it is attached. [Documentation](https://docs.nestjs.com/controllers#:~:text=Get(%27%3Aid%27)%0AfindOne(-,%40Param(%27id%27)%20id%3A%20string,-)%3A%20string%20%7B%0A%20%20return%20%60This)

I also think that it can get confused with the use of underscore as a markup of a private variable (a practice that is not mostly applied in typescript since we explicitly declare if a variable or function is private with the "private" access modifier).

2022-01-24 07:56 UTC, kamilmysliwiec commented on sample/06-mongoose/src/cats/cats.controller.ts
> +  async findOne(@Param("id") _id: string): Promise<Cat> {
Can we rename it to "id" instead?
```suggestion
  async findOne(@Param("id") id: string): Promise<Cat> {
```
Similarly in the method below and in the corresponding service class

2022-01-24 07:56 UTC, kamilmysliwiec commented
Can you run the "format" script too?

2022-01-24 18:43 UTC, asyncfinkd commented
> Can you run the "format" script too?

What is run "format" script?

2022-01-24 19:02 UTC, GalloaFranco commented
> > Can you run the "format" script too?
> 
> What is run "format" script?

In the mongoose sample project you have "format" [script](https://github.com/nestjs/nest/blob/master/sample/06-mongoose/package.json#:~:text=%22format%22%3A%20%22prettier%20%2D%2Dwrite%20%5C%22src/**/*.ts%5C%22%20%5C%22test/**/*.ts%5C%22%22%2C) declare in the package.json, this command run prettier.

2022-01-24 22:15 UTC, asyncfinkd commented
> > > Can you run the "format" script too?
> > 
> > 
> > What is run "format" script?
> 
> In the mongoose sample project you have "format" [script](https://github.com/nestjs/nest/blob/master/sample/06-mongoose/package.json#:~:text=%22format%22%3A%20%22prettier%20%2D%2Dwrite%20%5C%22src/**/*.ts%5C%22%20%5C%22test/**/*.ts%5C%22%22%2C) declare in the package.json, this command run prettier.

Fixed

2022-01-25 08:31 UTC, kamilmysliwiec commented on sample/06-mongoose/src/cats/cats.service.ts
> +  async findOne(_id: string): Promise<Cat> {
Can we rename it to "id">

2022-01-25 08:31 UTC, kamilmysliwiec commented on sample/06-mongoose/src/cats/cats.service.ts
> +  async delete(_id: string) {
Can we rename it to "id"?

2022-01-25 08:32 UTC, kamilmysliwiec commented on sample/06-mongoose/src/cats/cats.service.ts
> +    const deleteCat = await this.catModel
deleteCat -> deletedCat

2022-01-26 19:55 UTC, asyncfinkd commented
Fixed

2022-01-27 13:30 UTC, GalloaFranco commented on sample/06-mongoose/src/cats/cats.controller.ts
> +    return this.catsService.delete(_id);
For consistency with previous changes we can do the renaming here as well.
```ts
  @Delete(':id')
  async delete(@Param('id') id: string) {
    return this.catsService.delete(id);
 }
```

2022-01-28 08:33 UTC, asyncfinkd commented
Fixed

2022-01-28 10:19 UTC, merged

2022-01-28 10:19 UTC, kamilmysliwiec commented
lgtm