feat(common): do not use colors in CLI if not supported
nestjs/nest pull request #9278
Opened 2022-03-01 20:00 UTC by jonahsnider

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

`isColorAllowed()` will return `true` even when the terminal can't support colors.

Issue Number: N/A

## What is the new behavior?

Colors will be enabled if the `NO_COLOR` environment variable is not an empty string and `tty.WriteStream.prototype.hasColors()` returns `true`.

Requires Node.js v10.16.0 or newer.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

2022-03-01 20:29 UTC, jmcdo29 commented on packages/common/utils/cli-colors.util.ts
> +const isColorAllowed = () => !process.env.NO_COLOR && WriteStream.prototype.hasColors();
This is _mostly_ only used by the `ConsoleLogger`, but there are references to it in the `Injector.ts` file as well. If it was just the `ConsoleLogger` I'd say this is okay, or even checking `process.stdout.hasColors()` directly instead of needing the prototype, but I'm not sure how to handle if this check is coming from the `Injector.ts`

Overall, I don't _think_ this should be an issue, my only concern would be if someone is in an environment where `hasColors()` returns `false` but they want to force the use of colors.

2022-03-01 21:05 UTC, jonahsnider commented on packages/common/utils/cli-colors.util.ts
> +const isColorAllowed = () => !process.env.NO_COLOR && WriteStream.prototype.hasColors();
> even checking `process.stdout.hasColors()` directly instead of needing the prototype

That only checks `stdout` and not `stderr`. See https://github.com/nodejs/node/issues/40236 and https://github.com/nodejs/node/pull/40240 for discussion on exposing a better way to access `Writestream.prototype.hasColors()`.

> but I'm not sure how to handle if this check is coming from the `Injector.ts`

`isColorAllowed()` could be refactored to allow an optional parameter of the stream that is being written to and call `.hasColors()` on that directly.

> Overall, I don't _think_ this should be an issue, my only concern would be if someone is in an environment where `hasColors()` returns `false` but they want to force the use of colors.

They can use [the `FORCE_COLOR` environment variable](https://nodejs.org/dist/latest-v16.x/docs/api/tty.html#writestreamgetcolordepthenv).

2022-03-02 03:50 UTC, micalevisk requested changes
cool!

can you run `npm run format`

2022-03-14 12:58 UTC, merged

2022-03-14 12:58 UTC, kamilmysliwiec commented
LGTM

2022-03-17 05:51 UTC, mohamed-badaoui commented
The color should be allowed while the colors disappeared from my terminal: /

```
/app $  node -p -e  "!process.env.NO_COLOR && process.stdout.hasColors()" 
true
```

2022-03-19 06:27 UTC, mohamed-badaoui commented
**Tips**: For those who use Docker, do not forget to use the option in docker-compose service, otherwise the colors will not be displayed.

`tty: true`

2022-03-21 07:27 UTC, kamilmysliwiec commented
I think previously colors were displayed even if `tty` wasn't set to true, can you confirm @mohamed-badaoui? If so, we should revert this PR

2022-03-21 08:08 UTC, mohamed-badaoui commented
Yes before, the colors were displayed without passing tty param
I first added the TTY parameter set to True to have colors, but even with that, I now lose the interactive mode of the console.

I then tried to add this parameter to docker-compose:
''
stdin_open: true
''
But it does not work better. So I use the logger without color now :(