feat: allow custom log msg formatters
nestjs/nest pull request #9316
Opened 2022-03-09 15:58 UTC by stanimirovv

## PR Checklist
Implements option to have custom log formatters as discussed here:
https://github.com/nestjs/nest/issues/9281

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

- [X] Feature

## What is the current behavior?
Custom log message formaters aren't supported.

Issue Number: https://github.com/nestjs/nest/issues/9281

## What is the new behavior?
Custom log message formaters are supported

## Does this PR introduce a breaking change?
- [X] No

## Other information

2022-03-09 17:12 UTC, micalevisk commented on packages/common/test/services/logger.service.spec.ts
> +      let logger = new Logger();
```suggestion
      let logger: Logger;
```

as this will be instantianted on `beforeEach`

2022-03-10 08:45 UTC, stanimirovv commented on packages/common/test/services/logger.service.spec.ts
> +      let logger = new Logger();
Applied

2022-03-10 09:57 UTC, kamilmysliwiec commented on packages/common/services/console-logger.service.ts
>      const color = this.getColorByLogLevel(logLevel);
```suggestion
    const color = this.getColorByLogLevel(logLevel);
```
This line doesn't seem to be used anymore

2022-03-10 10:00 UTC, kamilmysliwiec commented on packages/common/services/console-logger.service.ts
> +    return `${pidMessage}${this.getTimestamp()} ${formattedLogLevel} ${contextMessage}${output}${timestampDiff}\n`;
I think this line:

```
`${pidMessage}${this.getTimestamp()} ${formattedLogLevel} ${contextMessage}${output}${timestampDiff}\n`
```
should be configurable. We could declare another protected method that receives these variables as input parameters (without colors applied). Perhaps that's actually how the `formatMessage` should look likely (we can move everything else back to the original location

2022-03-10 10:26 UTC, stanimirovv commented on packages/common/services/logger.service.ts
> +  public registerLocalInstanceRef(customInstance?: LoggerService) {
Understood.
The correct way to override the default ConsoleLogger is to use ```overrideLogger``` right ? 

I don't see a way to set the consoleLogger per instance. Should I add a setter for ```localInstance```

2022-03-10 10:26 UTC, stanimirovv commented on packages/common/services/console-logger.service.ts
> +    return `${pidMessage}${this.getTimestamp()} ${formattedLogLevel} ${contextMessage}${output}${timestampDiff}\n`;
Agreed, it's a simpler solution.

2022-03-10 10:29 UTC, kamilmysliwiec commented on packages/common/services/logger.service.ts
> +  public registerLocalInstanceRef(customInstance?: LoggerService) {
You can just instantiate your custom logger class (create a new instance) in your tests, no need to use `new Logger` wrapper in this case

2022-03-10 14:38 UTC, micalevisk requested changes

2022-03-10 14:38 UTC, micalevisk commented on packages/common/services/console-logger.service.ts
> +    pidMessage: string,
I think having this interface wouldn't be that easy to write the output that that Issue need because `pidMessage` is too tied with the default formatting and uses that `color`

Can you try to rewrite this `formatMessage` like this:

```
formatMessage(
  pid: number,
  logLevel: string,
  context: string,
  timestampDiff: number,
  output: string,
): string 
```

but then we'll need to change the `updateAndGetTimestampDiff` method to extract the coloring stuff from it and make it return a number instead of string.

And then make `formatMessage` return an string with the color applied instead of applying it on `printMessages`. But yeah, that could be a bit harsh

2022-03-10 14:43 UTC, stanimirovv commented on packages/common/services/console-logger.service.ts
> +    pidMessage: string,
Yeah I think this may be better, I will refactor it with your suggestions.

2022-03-11 09:39 UTC, stanimirovv commented on packages/common/services/console-logger.service.ts
> +    pidMessage: string,
@micalevisk  @kamilmysliwiec 

So with the latest changes we are more or less like the first version.
I am not 100% sure if the format version should just place the arguments or also be able to generate them.

The minimal implementation is here: https://github.com/stanimirovv/nest/commit/89d97652caafc26c379ae0268229c4fc3caf3cf2

The "accept less arguments and do more" implementation is here (also the current one):
https://github.com/stanimirovv/nest/blob/feat/custom-logger-formatters/packages/common/services/console-logger.service.ts#L192

Personally I lean towards the second version because you have more control - over colors for example.

What is the intent - to allow some control or full control ? 
If some control - go with https://github.com/stanimirovv/nest/commit/89d97652caafc26c379ae0268229c4fc3caf3cf2
If full go with - https://github.com/stanimirovv/nest/blob/feat/custom-logger-formatters/packages/common/services/console-logger.service.ts#L192

does that make sense ?

2022-03-11 09:45 UTC, kamilmysliwiec commented on packages/common/services/console-logger.service.ts
> +    pidMessage: string,
This approach https://github.com/stanimirovv/nest/commit/89d97652caafc26c379ae0268229c4fc3caf3cf2# better fits our needs but we should also allow opt-in coloring the messages. In this case, we should probably declare another dedicated method (let's say `colorize`) that takes the same set of arguments as `formatMessages` and adds colors. This method should be executed from within the `formatMessages` and have `protected` modifier to make it feasible to call it (if needed) from within the custom logger implementation.

2022-03-11 10:09 UTC, stanimirovv commented on packages/common/services/console-logger.service.ts
> +    pidMessage: string,
One final question - 

Wouldn't it be a simpler interface if `colorize` takes a single argument and returns it colorised ? 
`function colorize(str: string): string`
It will be called for the 2 parts of the message colored currently.
That way the user may add custom colorized elements to the log message.
But, again, depends on the intent.

The alternative is to have the following signature:
```
function colorize(
    pidMessage: string,
    formattedLogLevel: string,
    contextMessage: string,
    output: string,
    timestampDiff: string,): 

    [
      pidMessage: string,
      formattedLogLevel: string,
      contextMessage: string,
      output: string,
      timestampDiff: string,
    ]
```

2022-03-11 10:15 UTC, kamilmysliwiec commented on packages/common/services/console-logger.service.ts
> +    pidMessage: string,
Yeah, I think as long as we make `getColorByLogLevel` protected as well (to make it accessible) it could take two arguments (one being a message to format and the second - optional - color to be used that defaults to `this.getColorByLogLever()`)

2022-03-11 17:25 UTC, stanimirovv commented on packages/common/services/console-logger.service.ts
> +    pidMessage: string,
I think we should be very close:

1. I extracted the colorize method and moved all logic having to do with colors into the formatMessage function as discussed
2. I took the liberty to extract one more protected message - stringifyMessage I can change it to private, but it felt like something that should also optionally be configurable -> the way the objects are serialized.

2022-03-11 17:31 UTC, jmcdo29 commented on packages/common/services/console-logger.service.ts
> +      const pidMessage = `[Nest] ${process.pid}  - `;
Would it be possible to move this to it's own `protected` method so that it could be overridden if desired (like using the `threadId` instead of `process.pid`)? That's what #9281 was about to begin with, right? Maybe even just something like `conts pidMessage = `[Nest] ${this.getPid()} - `

2022-03-11 17:43 UTC, stanimirovv commented on packages/common/services/console-logger.service.ts
> +      const pidMessage = `[Nest] ${process.pid}  - `;
@jmcdo29 sounds like a good candidate for a protected method, on it

2022-03-11 18:13 UTC, stanimirovv commented on packages/common/services/console-logger.service.ts
> +      const pidMessage = `[Nest] ${process.pid}  - `;
@jmcdo29 done - maybe the function shoud take no arguments that way when it is overriden it won't have an extra unused argument. That being said - keeping it pure may be the better option. 

Thoughts?

2022-03-13 17:06 UTC, jmcdo29 approved these changes

2022-03-14 12:57 UTC, kamilmysliwiec commented
LGTM

2022-03-14 12:57 UTC, merged