fix(platform-fastify): fix typo
nestjs/nest pull request #9389
Opened 2022-03-26 18:32 UTC by wiasliaw

## PR Type

What kind of change does this PR introduce?

- [x] Other... Please describe: Comment in `@platform-fastify` is wrong.

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

2022-03-26 19:36 UTC, jmcdo29 approved these changes

2022-03-26 22:43 UTC, Tony133 approved these changes

2022-03-26 22:44 UTC, Tony133 requested changes

2022-03-26 22:44 UTC, Tony133 commented on packages/platform-fastify/index.ts
>   * Copyright(c) 2017 - 2021 Kamil Mysliwiec
```suggestion
 * Copyright(c) 2017 - 2022 Kamil Mysliwiec
```

2022-03-26 22:46 UTC, Tony133 commented on packages/platform-fastify/index.ts
>   * Copyright(c) 2017 - 2021 Kamil Mysliwiec
I think maybe even updating copyright comments wouldn't hurt, would it? anyway that's okay.

2022-03-28 05:23 UTC, wiasliaw commented on packages/platform-fastify/index.ts
>   * Copyright(c) 2017 - 2021 Kamil Mysliwiec
Yes, I can help to update.

2022-03-28 07:21 UTC, merged