chore: update fastify deps
nestjs/nest pull request #9507
Opened 2022-04-29 23:01 UTC by alexfriesen

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Fastify moved a lot of packages around and left the remaining ones with this deprecation message: `[FST_MODULE_DEP_FASTIFY-STATIC] FastifyWarning.fastify-static: fastify-static has been deprecated. Use @fastify/static@5.0.0 instead.`

Issue Number: N/A

## What is the new behavior?

The same

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2022-04-30 14:40 UTC, micalevisk requested changes
I guess we need to touch the `package-lock.json` file as well, right?

2022-05-01 11:36 UTC, alexfriesen commented
> I guess we need to touch the `package-lock.json` file as well, right?

Yes you are right sorry about that. The package-lock files are updated as well

2022-05-01 11:36 UTC, micalevisk approved these changes

2022-05-01 19:33 UTC, Tony133 approved these changes

2022-05-03 09:09 UTC, flamewow commented on packages/platform-fastify/package.json
> +    "fastify": "3.29.0",
can we add peerDependencies (I know it was not there, but we can add it as part of the PR)

```
  "peerDependencies": {
...
    "@fastify/static": "^5.0.0",
    "point-of-view": "^5.0.0"
  }
```

2022-05-03 09:11 UTC, flamewow commented
can you check platform-fastify/interfaces/external/* and sync if needed? I believe fastifyStaticOptions got updated

2022-05-04 08:12 UTC, kamilmysliwiec commented on packages/platform-fastify/package.json
> +    "point-of-view": "^5.0.0"
we should also add the `peerDependenciesMeta` entry, flagging these deps as _optional_, see example here https://github.com/nestjs/graphql/blob/master/packages/apollo/package.json#L52

2022-05-04 09:31 UTC, flamewow approved these changes

2022-05-07 10:18 UTC, Tony133 approved these changes

2022-05-17 11:24 UTC, merged