chore(): upgrade version fastify 4.x
nestjs/nest pull request #9746
Opened 2022-06-08 20:49 UTC by Tony133

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Upgrade version fastify 4.x

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

To be added to NestJS v9

2022-06-10 10:13 UTC, tugascript commented
Shouldn't you have to update the plugins as well? Those versions are deprecated.

fastify-cors -> @fastify/cors 
fastify-multipart -> @fastify/multipart

2022-06-10 10:42 UTC, Tony133 commented
I haven't updated them because they have already been integrated into the v9 branch in this PR (see here https://github.com/nestjs/nest/pull/9507) 😁. It was just missing to update the version of fastify because it came out a couple of days ago.

2022-06-13 12:50 UTC, kamilmysliwiec commented
Can you use the `9.0.0` branch as a target branch?

2022-06-13 19:09 UTC, jmcdo29 requested changes

2022-06-13 19:09 UTC, jmcdo29 commented on package.json
>      "@types/supertest": "2.0.12",
Remove the git conflict markers and resolve the conflict please

2022-06-13 19:09 UTC, jmcdo29 commented on package.json
> ->>>>>>> 1d55a14e9 (chore(): upgrade version fastify 4.x)
Remove the git conflict markers and resolve the conflict please

2022-06-13 19:29 UTC, closed without merging