feat(core): middleware runs once for matching route
nestjs/nest pull request #9809
Opened 2022-06-20 04:17 UTC by rychardvale

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently, routes that has dynamic params can trigger a middleware multiple times for a single request if matches another static route inside the controller.

Issue Number: [#1628](https://github.com/nestjs/nest/issues/1628)

## What is the new behavior?
Routes will only trigger the middleware for the exact path match.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2022-06-24 18:15 UTC, micalevisk commented on packages/core/middleware/builder.ts
> +        .filter(route => route.path.indexOf(':') >= 0)
```suggestion
        .filter(route => route.path.includes(':'))
```

2022-06-24 19:13 UTC, rychardvale commented on packages/core/middleware/builder.ts
> +        );
Absolutely! Will do.

2022-06-25 02:48 UTC, micalevisk approved these changes

2022-06-26 14:40 UTC, Tony133 requested changes
A little convention/syntax fix while otherwise fine, but let's see what Kamil thinks.

2022-06-26 14:40 UTC, Tony133 commented on packages/core/middleware/builder.ts
> +        if (routeMatch === undefined) return route;
```suggestion
        if (routeMatch === undefined) {
         return route;
        }
```

2022-06-26 19:11 UTC, Tony133 approved these changes

2022-06-28 18:30 UTC, hebertcisco approved these changes

2023-06-12 07:47 UTC, merged