feat(): add `@CacheExclude()`
nestjs/nest pull request #9999
Opened 2022-07-21 23:22 UTC by agent-ly

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ X ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ X ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ X ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Add `CacheExclude()` to allow endpoint level control over whether or not should it be excluded from being cached

## Does this PR introduce a breaking change?
- [ ] Yes
- [ X ] No

## Other information

2022-07-21 23:50 UTC, jmcdo29 requested changes
Great work! Made a minor suggestion, but looks good

2022-07-21 23:50 UTC, jmcdo29 commented on packages/common/cache/interceptors/cache.interceptor.ts
> +    );
Could we make this a `getAllAndMerge` to handle if `@CacheExclude()` is called on the class and not just the method? In case the interceptor is bound globally but a full controller should be skipped over.

```suggestion
    const cacheExcludeMetadata = this.reflector.getAllAndMerge(
      CACHE_EXCLUDE_METADATA,
      context.getClass(),
      context.getHandler(),
    );
```

2022-07-22 01:19 UTC, jmcdo29 approved these changes

2022-07-22 05:55 UTC, Tony133 approved these changes

2022-07-22 07:21 UTC, kamilmysliwiec commented
I'm not sure how I feel about this PR. AFAIR this has been discussed in the past and we decided not to add more functionalities to the `cache` subpackage, especially such features that can be implemented by the end-user (customized through the `trackBy` method - that's exactly why we made it feasible to simply extend the guard & override its "trackBy" logic). To me, this doesn't sound like a necessary addition, given that it's non-blocking & not very complex to implement on your own

2022-07-22 07:30 UTC, agent-ly commented
> I'm not sure how I feel about this PR. AFAIR this has been discussed in the past and we decided not to add more functionalities to the `cache` subpackage, especially such features that can be implemented by the end-user (customized through the `trackBy` method - that's exactly why we made it feasible to simply extend the guard & override its "trackBy" logic). To me, this doesn't sound like a necessary addition, given that it's non-blocking & not very complex to implement on your own

While I agree that it is very trivial to implement this yourself, you should not have to. It is a vital feature that solves many general use cases and greatly improves developer experience, which is ultimately the goal.

2022-07-22 07:40 UTC, kamilmysliwiec commented
I agree that this is generally a vital functionality (of the cache feature), but we don't want to keep the `CacheModule` in the `@nestjs/common` package long-term in the first place. We'll eventually move it to its own, dedicated package, very likely as part of the next major release and this is when we could start baking in more features (so they are available out-of-the-box).

2022-07-28 09:12 UTC, closed without merging

2022-08-15 14:42 UTC, ZanMinKian commented
> we don't want to keep the `CacheModule` in the `@nestjs/common` package long-term in the first place. We'll eventually move it to its own, dedicated package, very likely as part of the next major release

Is that mean it will release a package `@nestjs/cache` and deprecate the `CacheModule` in `@nestjs/common`? Like `HttpModule`?

Maybe we can release a package `@nestjs/cache` early and deprecate the `CacheModule` of `@nestjs/common` in next `MINOR` version. Because it have no breaking change in fact.

Should `ClassSerializerInterceptor` be moved to its own package? Like `@nestjs/serialize`. IMO, progressive framework should keep terse. For example, I want to add some features to ClassSerializerInterceptor, but I don't want to upgrade my app from nest8 to nest9 for other breaking change reason.